version: '3'

services:
  app:
    image: node:6
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "cd ./server && npm run start.dev"
    ports:
      - 3000:3000
    links:
      - mongodb

  mongodb:
     image: mongo
     ports:
       - 27017:27017

  mongo.restore:
    image: mongo-data111111
    volumes:
      - .:/app
    working_dir: /app
    links:
      - mongodb

  mongo.restoreEWA:
      image: mongo-data111111
      volumes:
        - .:/app
      working_dir: /app
      links:
        - mongodb

  mongo.dump:
      image: mongo
      volumes:
        - .:/app
      working_dir: /app
      links:
        - mongodb

